import type { Metadata } from "next";
import "./globals.css";
import Header from "@/_components/Header";
import TopBar from "@/_components/TopBar";
import { Josefin_Sans } from "next/font/google";

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${josefinSans.className} antialiased`}>
      <body>
        <TopBar />
        <Header />
        {children}
      </body>
    </html>
  );
}
